// ============================================
// BẢNG GIÁ / PRICING
// ============================================

export const PRICING_PACKAGES = {
  vi: [
    {
      name: 'Cơ Bản',
      icon: 'Zap',
      price: '1.990.000',
      originalPrice: '2.800.000',
      description: 'Hoàn hảo cho gia đình',
      features: [
        '1 bức tranh gạo 30x40cm',
        'Khung kính tiêu chuẩn',
        'Chữ thư pháp: Tài - Lộc',
        'Chứng nhận tác phẩm',
        'Giao hàng miễn phí nội thành',
        'Bảo hành khung 6 tháng',
      ],
      popular: false,
    },
    {
      name: 'Cao Cấp',
      icon: 'Crown',
      price: '3.490.000',
      originalPrice: '4.990.000',
      description: 'Lựa chọn phổ biến nhất',
      features: [
        '1 bức tranh gạo 40x50cm',
        'Khung kính cao cấp mạ vàng',
        'Chữ thư pháp: Phúc - Lộc - Thọ',
        'Chứng nhận + giấy khen nghệ nhân',
        'Giao hàng toàn quốc miễn phí',
        'Bảo hành khung 12 tháng',
        'Tư vấn phong thủy miễn phí',
      ],
      popular: true,
    },
    {
      name: 'VIP',
      icon: 'Sparkles',
      price: '5.990.000',
      originalPrice: '8.500.000',
      description: 'Dành cho người sành điệu',
      features: [
        '1 bức tranh gạo 50x70cm',
        'Khung gỗ quý + kính chống phản quang',
        'Chữ tùy chọn theo yêu cầu',
        'Chứng nhận cao cấp có dấu đỏ',
        'Giao hàng VIP + lắp đặt tận nhà',
        'Bảo hành trọn đời',
        'Tư vấn phong thủy chuyên sâu',
        'Quà tặng kèm trị giá 500k',
      ],
      popular: false,
    },
  ],
  en: [
    {
      name: 'Basic',
      icon: 'Zap',
      price: '1,990,000',
      originalPrice: '2,800,000',
      description: 'Perfect for family',
      features: [
        '1 rice art 30x40cm',
        'Standard glass frame',
        'Calligraphy: Wealth - Fortune',
        'Certificate of authenticity',
        'Free delivery in city',
        '6-month frame warranty',
      ],
      popular: false,
    },
    {
      name: 'Premium',
      icon: 'Crown',
      price: '3,490,000',
      originalPrice: '4,990,000',
      description: 'Most popular choice',
      features: [
        '1 rice art 40x50cm',
        'Premium gold-plated glass frame',
        'Calligraphy: Fortune - Prosperity - Longevity',
        'Certificate + artisan commendation',
        'Free nationwide delivery',
        '12-month frame warranty',
        'Free feng shui consultation',
      ],
      popular: true,
    },
    {
      name: 'VIP',
      icon: 'Sparkles',
      price: '5,990,000',
      originalPrice: '8,500,000',
      description: 'For connoisseurs',
      features: [
        '1 rice art 50x70cm',
        'Precious wood frame + anti-reflective glass',
        'Custom text on request',
        'Premium certificate with red seal',
        'VIP delivery + home installation',
        'Lifetime warranty',
        'In-depth feng shui consultation',
        'Complimentary gift worth 500k',
      ],
      popular: false,
    },
  ],
};
